name: Deploy Azure Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r api/requirements.txt
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: erp-functions
          package: ./api
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}
